### ISSUE TITLE
1.16.4: Incompatible plugin: GroupManager

### ISSUE THREAD

**Issue by Caticer** [Caticer/1.16.x_server#2]
```
[20:44:53] [Server thread/INFO]: [GroupManager] Bukkit Permissions Updated!
[20:44:53] [Craft Scheduler Thread - 8/INFO]: [GroupManager] There was an issue parsing the version string.
[20:44:53] [Craft Scheduler Thread - 8/WARN]: java.lang.NullPointerException: Cannot invoke "String.split(String)" because "version" is null
[20:44:53] [Craft Scheduler Thread - 8/WARN]:   at org.anjocaido.groupmanager.Tasks.UpdateTask.parseVersion(UpdateTask.java:188)
[20:44:53] [Craft Scheduler Thread - 8/WARN]:   at org.anjocaido.groupmanager.Tasks.UpdateTask.updateCheck(UpdateTask.java:167)
[20:44:53] [Craft Scheduler Thread - 8/WARN]:   at org.anjocaido.groupmanager.Tasks.UpdateTask.run(UpdateTask.java:54)
[20:44:53] [Craft Scheduler Thread - 8/WARN]:   at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81)
[20:44:53] [Craft Scheduler Thread - 8/WARN]:   at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[20:44:53] [Craft Scheduler Thread - 8/WARN]:   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[20:44:53] [Craft Scheduler Thread - 8/WARN]:   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[20:44:53] [Craft Scheduler Thread - 8/WARN]:   at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by Caticer** [comment]
Fixed with latest update
